### ISSUE TITLE
신규 홈페이지의 제공 기능 및 컨셉 정리

### ISSUE THREAD

**Issue by kkame** [ModernPUG/modernpug.org#4]
## 컨셉

- php 개발과 관련된 블로그 정보를 제공합니다 (기존 allblog와 통합)
- php에 관련한 구인 구직 정보를 제공합니다
- php와 관련한 개발 지식을 모아서 보여줍니다
- 공식 슬랙 초대장 발송을 합니다
- 후원사의 정보를 제공합니다
- 운영진 정보를 제공합니다

**Comment by smartbos** [comment]
할 게 많네요!

**Comment by smartbos** [comment]
문득, 제가 혼자 깨작깨작 만들던 PHP 사용하는 웹 애플리케이션 목록도 붙이면 좋겠단 생각이 들었어요 ㅎㅎ

**Comment by smartbos** [comment]
PHP 관련 교육, 세미나, 모임 정보도 모아서 볼 수 있으면 어떨까요~ (하고 싶은거 막 적는 중 ㅋㅋㅋ)

**Comment by kkame** [comment]
좋은 거 같아요
아이디어는 많이 주시면 좋을 것 같아요
사이트의 방향성을 잡는데 도움이 많이 될 거 같고
기능 자체는 하나씩 개발해 나가면 되는거니깐요

**Comment by kkame** [comment]
추가적으로 고민중인건 php 관련 메뉴얼들이 좀 산재해 있는 느낌인데
이걸 모아서 보여주는 형태로 가든가 (링크든 사이트내든)
모임에서 제공하는 php the right way 같은 경우는 사이트 내로 통합하는 형태로 해도 괜찮지 않을까 생각해요

**Comment by smartbos** [comment]
> 추가적으로 고민중인건 php 관련 메뉴얼들이 좀 산재해 있는 느낌인데
> 이걸 모아서 보여주는 형태로 가든가 (링크든 사이트내든)
> 모임에서 제공하는 php the right way 같은 경우는 사이트 내로 통합하는 형태로 해도 괜찮지 않을까 생각해요

좋네요~ 선링크, 후통합 가시죠!

**Comment by smartbos** [comment]
Q&A 통합~

**Comment by kkame** [comment]
php 관련 릴리즈 소식 업데이트 및 주간 슬랙 알림 추가
ex) xdebug x.xx.xx 버전 출시, 라라벨 x.xx.xx. 버전 출시

**Comment by appkr** [comment]
와우! 고생 많으시네요. 도움은 못 드리고ㅜㅜ, 따봉 하나 남기고 갑니다. 👍

**Comment by kkame** [comment]
홈페이지를 오픈 할 예정이므로 컨셉관련 이슈는 닫도록 하겠습니다.
미 개발된 사항은 신규 이슈로 모두 등록하였고 
이후에 추가적인 기능 개발의 경우 모두 개별 이슈로 등록 후 관리하도록 하겠습니다.
