### ISSUE TITLE
로그아웃 경로

### ISSUE THREAD

**Issue by RedgooseDev** [ModernPUG/modernpug.org#7]
`/auth/logout` 경로를 post로 넘기는데 토큰때문에 어쩔수 없는것인가요?
그냥 `<a href="/auth/logout">logout</a>`으로 보낼 수 있었으면 합니다.

**Comment by koojunho** [comment]
아~ 아뇨 get 으로 하면 게시판등에서 이 글 한 번 보라며 상대를 로그아웃 시키거나 탈퇴시키는 게 가능해지는데 그것을 막기위한 방법입니다.

**Comment by RedgooseDev** [comment]
일반적으로 get으로 logout으로 넘어가면 로그아웃이 되는데... 이건 분명히 해결방법이 있을거라고 보이는걸요...
로그아웃 하나 하는데 post로 넘기는건 여태까지 경험에서는 처음보고 여전히 납득이 안됩니다. 보통 로그아웃 하면 세션을 비우지 않나요? -_-;

**Comment by koojunho** [comment]
저는 해킹기법을 잘 몰라서 저역시 강제 로그아웃이 강제 탈퇴만큼 리스키하다고는 생각은 안드는데요. 어떤 기법이 있는지 찾아보지는 않았고 옛 구현 기억따라 별 판단 없이 추가한 form 이기는 해요. 세션을 비우지 않느냐고 물으신 부분은 어떤 의미인지 잘 이해를 못했습니다.

![2016-03-04 3 56 41](https://cloud.githubusercontent.com/assets/334933/13505604/2bfe0b4e-e1bd-11e5-92ae-c7ab6c5c67fe.png)

참고로 위는 페이스북의 로그아웃 부분 대충 살펴본거. ㅋㅋ
그런데 질문주셔서 제가 궁금한 것은 로그아웃이 post 여서 생기는 단점이 있나요? http 헤더 사이즈는 비등비등 할 것 같고요.

**Comment by koojunho** [comment]
http://stackoverflow.com/questions/3521290/logout-get-or-post/14587231#14587231

요즘은 크롬 브라우저 등에서 특정 url을 미리 불러오는 기능을 제공하고 있어서 logout 은 post 로 만드는 추세인가보네요. 브라우저가 자동으로 logout 을 누르고 다니는 문제가 있나 보네요.

**Comment by RedgooseDev** [comment]
```
<nav class="navigation">
	<ul>
		<li><a href="#">mypage</a></li>
		<li>
			<form action="logout" method="post">
				<button type="submit">logout</button>
			</form>
		</li>
	</ul>
</nav>
```

상단 헤더영역인데 네비게이션을 위와같이 웃기지도 않는형태로 코딩해야합니다.
아니면 스크립트 처리해야하는데 로그아웃 하나 하자고 스크립트 처리하는것도 웹접근성에 아닌거 같구요...
보아하니 구글도 단순히 링크로 로그아웃 가능하구요. 페이스북은 스크립트 처리해놨네요.

결론은 스크립트를 쓰던지 링크를 쓰던지간데 `<a href="#">logout</a>` 형태의 링크를 원합니다.

**Comment by koojunho** [comment]
Form이 문제인거군요. `<a href="#">logout</a>` 로 하시죠~

**Comment by koojunho** [comment]
logout 뿐만 아니라 '삭제' 버튼도 <a> 태그로 처리하기로 협의.
