### ISSUE TITLE
위키 데이터베이스 테이블이 설치되지 않는거 같습니다.

### ISSUE THREAD

**Issue by RedgooseDev** [ModernPUG/modernpug.org#9]
```
Redgoose-Mac:modernpug.org redgoose$ php artisan migrate:reset && php artisan migrate
Rolled back: 2016_01_26_061747_create_qna_tables
Rolled back: 2016_01_26_025848_create_social_logins_table
Rolled back: 2014_10_12_100000_create_password_resets_table
Rolled back: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_01_26_025848_create_social_logins_table
Migrated: 2016_01_26_061747_create_qna_tables
```
명령어는 이렇게 치면서 리셋을 했는데 메세지를 이렇구요...

테이블을 추가하는 뭔가 더 필요한거 같네요. 아니면 업데이트가 필요한지도요...

**Comment by koojunho** [comment]
1. `php artisan vendor:publish` 해보시면 패키지쪽의 리소스 중 필요한 것을 app 쪽으로 보내게 되고요.
1. `php artisan vendor:publish --force` 해보시면 이미 복사가 되어 있는 경우 덮어쓰기를 안하는데 강제로 해줍니다.

2)가 현재 config를 덮는 문제가 있는데 1) 이 진행이 안됐다면 1번 하고 migrate 해주시고 안되면 2) 를 해봐주세요.

**Comment by RedgooseDev** [comment]
1번 시도해보고 `php artisan migrate:reset && php artisan migrate` 명령어 실행하니 잘되네요.
감사합니다.
